#!/bin/bash
# generate-changelog — structured CHANGELOG.md from git history since last tag
# Usage: ./changelog.sh [since_tag] [output_file]
# Default: since latest tag, output CHANGELOG.md

set -euo pipefail
IFS=$'\n\t'

SINCE="${1:-$(git describe --tags --abbrev=0 2>/dev/null || git rev-list --max-parents=0 HEAD)}"
OUT="${2:-CHANGELOG.md}"
REPO=$(basename "$(git rev-parse --show-toplevel 2>/dev/null)" 2>/dev/null || echo "repo")

if ! git rev-parse --git-dir >/dev/null 2>&1; then
    echo "Error: Not a git repository" >&2
    exit 1
fi

# Collect commits since tag
commits=$(git log "$SINCE..HEAD" --pretty=format:"%s" 2>/dev/null || git log --pretty=format:"%s")

ADDED=(); FIXED=(); CHANGED=(); REMOVED=()

while IFS= read -r line; do
    line=$(echo "$line" | sed 's/^ *//;s/ *$//')
    [ -z "$line" ] && continue
    if echo "$line" | grep -qiE '^(add|feat|Add|Feat)'; then ADDED+=("$line")
    elif echo "$line" | grep -qiE '^(fix|bug|hotfix|Fix|Bug|Hotfix)'; then FIXED+=("$line")
    elif echo "$line" | grep -qiE '^(remove|drop|delete|Remove|Drop|Delete)'; then REMOVED+=("$line")
    else CHANGED+=("$line")
    fi
done <<< "$commits"

# Build CHANGELOG
DATE=$(date +%Y-%m-%d)
VER=$(git describe --tags --abbrev=0 2>/dev/null || echo "Unreleased")

{
    echo "# $REPO — Changelog"
    echo ""
    echo "## [$VER] — $DATE"
    echo ""

    section() {
        local title="$1"; shift
        local -n items=$1
        [ ${#items[@]} -eq 0 ] && return
        echo "### $title"
        echo ""
        for item in "${items[@]}"; do
            echo "- $item"
        done
        echo ""
    }

    section "Added" ADDED
    section "Fixed" FIXED
    section "Changed" CHANGED
    section "Removed" REMOVED

    echo "---"
    echo "*Generated by changelog-generator skill*"
} > "$OUT"

echo "✅ CHANGELOG written to $OUT"
echo "   Commits: $(echo "$commits" | wc -l) | Categories: Added=${#ADDED[@]} Fixed=${#FIXED[@]} Changed=${#CHANGED[@]} Removed=${#REMOVED[@]}"
